acc_iou_threshold: 0.5
alpha: 0.25
bs: 16
bsv: 16
devices: 0
do_norm: false
ds_to_use: vg_split
emb_dim: 300
epochs: 10
gamma: 2
lamb_reg: 1
load_normally: true
load_opt: false
lr: 0.0001
lstm_dim: 128
matching_threshold: 0.6
mdl_to_use: retina
nw: 4
nwv: 4
opt_fn: Adam
opt_fn_params:
  betas:
  - 0.9
  - 0.99
patience: 2
ratios: '[1/2, 1, 2]'
reduce_factor: 0.1
resize_img:
- 300
- 300
resume: true
resume_path: ''
scale_factor: 4
scales: '[1, 2**(1/3), 2**(2/3)]'
strict_load: true
tmp_path: ./tmp
use_bidirectional: true
use_focal: true
use_img: true
use_lang: true
use_multi: true
use_reduce_lr_plateau: true
use_same_atb: true
use_softmax: false
